import type { Store } from './entities';

export const PREDEFINED_STORES: Store[] = [
  {
    id: 'store1',
    nom: 'SuperMart Dovv',
    categorie: 'supermarché',
    localisation: {
      latitude: 48.8566,
      longitude: 2.3522,
      adresse: '123 Rue de Paris, 75001 Paris, France',
    },
    horaires: [
      { jour: 'Lundi', ouverture: '08:00', fermeture: '20:00' },
      { jour: 'Mardi', ouverture: '08:00', fermeture: '20:00' },
      { jour: 'Mercredi', ouverture: '08:00', fermeture: '20:00' },
      { jour: 'Jeudi', ouverture: '08:00', fermeture: '20:00' },
      { jour: 'Vendredi', ouverture: '08:00', fermeture: '20:00' },
      { jour: 'Samedi', ouverture: '09:00', fermeture: '19:00' },
      { jour: 'Dimanche', ouverture: '10:00', fermeture: '18:00' },
    ],
    contact: {
      telephone: '+33 1 23 45 67 89',
      email: 'contact@supermartparis.fr',
      siteWeb: 'https://supermartparis.fr',
    },
    articles: [
      {
        id: 'item1',
        storeId: 'store1',
        nom: 'Tomates',
        categorie: 'légume',
        prixUnitaire: 2.5,
        unite: 'kg',
        stockDisponible: 100,
        imageUrl: 'assets/images/tomates.jpg',
        description: 'Tomates fraîches de saison, cultivées localement.',
        marque: 'BioMart',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item2',
        storeId: 'store1',
        nom: 'Poulet Fermier',
        categorie: 'viande',
        prixUnitaire: 8.0,
        unite: 'kg',
        stockDisponible: 50,
        imageUrl: 'assets/images/poulet.jpg',
        description: 'Poulet fermier bio, élevé en plein air.',
        marque: 'FermeLocale',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item3',
        storeId: 'store1',
        nom: 'Riz Basmati',
        categorie: 'céréale',
        prixUnitaire: 3.0,
        unite: 'kg',
        stockDisponible: 200,
        imageUrl: 'assets/images/riz.jpg',
        description: 'Riz basmati de qualité supérieure.',
        marque: 'GoldenGrain',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item4',
        storeId: 'store1',
        nom: 'Lait Entier',
        categorie: 'produit laitier',
        prixUnitaire: 1.2,
        unite: 'l',
        stockDisponible: 150,
        imageUrl: 'assets/images/lait.jpg',
        description: 'Lait entier pasteurisé.',
        marque: 'Lactalis',
        dateMiseAJour: '2025-06-01',
      },
    ],
    promotions: [
      {
        articleId: 'item1',
        reduction: 10, // 10%
        dateDebut: '2025-06-01',
        dateFin: '2025-06-15',
      },
      {
        articleId: 'item3',
        reduction: 15, // 15%
        dateDebut: '2025-06-05',
        dateFin: '2025-06-20',
      },
    ],
    // Added dateCreation and dateMiseAJour
    dateCreation: '2025-06-01',
    dateMiseAJour: '2025-06-05',
  },
  {
    id: 'store2',
    nom: 'Poissonnerie de la Mer',
    categorie: 'poissonnerie',
    localisation: {
      latitude: 48.8606,
      longitude: 2.3422,
      adresse: '45 Quai de Seine, 75004 Paris, France',
    },
    horaires: [
      { jour: 'Lundi', ouverture: '09:00', fermeture: '18:00' },
      { jour: 'Mardi', ouverture: '09:00', fermeture: '18:00' },
      { jour: 'Mercredi', ouverture: '09:00', fermeture: '18:00' },
      { jour: 'Jeudi', ouverture: '09:00', fermeture: '18:00' },
      { jour: 'Vendredi', ouverture: '09:00', fermeture: '18:00' },
      { jour: 'Samedi', ouverture: '09:00', fermeture: '17:00' },
      { jour: 'Dimanche', ouverture: 'fermé', fermeture: 'fermé' },
    ],
    contact: {
      telephone: '+33 1 98 76 54 32',
      email: 'info@poissonneriedelamer.fr',
    },
    articles: [
      {
        id: 'item5',
        storeId: 'store2',
        nom: 'Saumon Frais',
        categorie: 'poisson',
        prixUnitaire: 15.0,
        unite: 'kg',
        stockDisponible: 30,
        imageUrl: 'assets/images/saumon.jpg',
        description: 'Saumon frais d’Atlantique, idéal pour sushi ou grillades.',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item6',
        storeId: 'store2',
        nom: 'Crevettes',
        categorie: 'poisson',
        prixUnitaire: 12.0,
        unite: 'kg',
        stockDisponible: 40,
        imageUrl: 'assets/images/crevettes.jpg',
        description: 'Crevettes roses fraîches.',
        dateMiseAJour: '2025-06-01',
      },
    ],
    promotions: [],
    // Added dateCreation and dateMiseAJour
    dateCreation: '2025-06-01',
    dateMiseAJour: '2025-06-05',
  },
  {
    id: 'store3',
    nom: 'Épicerie Bio Local',
    categorie: 'épicerie',
    localisation: {
      latitude: 48.8656,
      longitude: 2.3622,
      adresse: '78 Rue Bio, 75003 Paris, France',
    },
    horaires: [
      { jour: 'Lundi', ouverture: '10:00', fermeture: '19:00' },
      { jour: 'Mardi', ouverture: '10:00', fermeture: '19:00' },
      { jour: 'Mercredi', ouverture: '10:00', fermeture: '19:00' },
      { jour: 'Jeudi', ouverture: '10:00', fermeture: '19:00' },
      { jour: 'Vendredi', ouverture: '10:00', fermeture: '19:00' },
      { jour: 'Samedi', ouverture: '10:00', fermeture: '18:00' },
      { jour: 'Dimanche', ouverture: 'fermé', fermeture: 'fermé' },
    ],
    contact: {
      telephone: '+33 1 56 78 90 12',
      siteWeb: 'https://epicerielocalbio.fr',
    },
    articles: [
      {
        id: 'item7',
        storeId: 'store3',
        nom: 'Pommes Bio',
        categorie: 'fruit',
        prixUnitaire: 3.0,
        unite: 'kg',
        stockDisponible: 80,
        imageUrl: 'assets/images/pommes.jpg',
        description: 'Pommes bio cultivées sans pesticides.',
        marque: 'VergerBio',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item8',
        storeId: 'store3',
        nom: 'Miel Artisanal',
        categorie: 'autre',
        prixUnitaire: 6.5,
        unite: 'unité',
        stockDisponible: 20,
        imageUrl: 'assets/images/miel.jpg',
        description: 'Miel artisanal de lavande.',
        marque: 'MielDuTerroir',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item9',
        storeId: 'store3',
        nom: 'Poivre Noir',
        categorie: 'épice',
        prixUnitaire: 4.0,
        unite: 'g',
        stockDisponible: 100,
        imageUrl: 'assets/images/poivre.jpg',
        description: 'Poivre noir en grains, 100g.',
        marque: 'ÉpicesPure',
        dateMiseAJour: '2025-06-01',
      },
    ],
    promotions: [
      {
        articleId: 'item7',
        reduction: 20, // 20%
        dateDebut: '2025-06-01',
        dateFin: '2025-06-10',
      },
    ],
    // Added dateCreation and dateMiseAJour
    dateCreation: '2025-06-01',
    dateMiseAJour: '2025-06-05',
  },
  {
    id: 'store4',
    nom: 'Marché Local de Lyon',
    categorie: 'marché local',
    localisation: {
      latitude: 45.7640,
      longitude: 4.8357,
      adresse: 'Place du Marché, 69002 Lyon, France',
    },
    horaires: [
      { jour: 'Lundi', ouverture: 'fermé', fermeture: 'fermé' },
      { jour: 'Mardi', ouverture: '07:00', fermeture: '13:00' },
      { jour: 'Mercredi', ouverture: '07:00', fermeture: '13:00' },
      { jour: 'Jeudi', ouverture: '07:00', fermeture: '13:00' },
      { jour: 'Vendredi', ouverture: '07:00', fermeture: '13:00' },
      { jour: 'Samedi', ouverture: '07:00', fermeture: '14:00' },
      { jour: 'Dimanche', ouverture: '07:00', fermeture: '14:00' },
    ],
    contact: {
      telephone: '+33 4 12 34 56 78',
    },
    articles: [
      {
        id: 'item10',
        storeId: 'store4',
        nom: 'Carottes',
        categorie: 'légume',
        prixUnitaire: 1.8,
        unite: 'kg',
        stockDisponible: 60,
        imageUrl: 'assets/images/carottes.jpg',
        description: 'Carottes fraîches du marché.',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item11',
        storeId: 'store4',
        nom: 'Fromage de Chèvre',
        categorie: 'produit laitier',
        prixUnitaire: 5.0,
        unite: 'unité',
        stockDisponible: 25,
        imageUrl: 'assets/images/fromage.jpg',
        description: 'Fromage de chèvre artisanal.',
        dateMiseAJour: '2025-06-01',
      },
    ],
    promotions: [],
    // Added dateCreation and dateMiseAJour
    dateCreation: '2025-06-01',
    dateMiseAJour: '2025-06-05',
  },
  {
    id: 'store5',
    nom: 'Boucherie Tradition',
    categorie: 'boucherie',
    localisation: {
      latitude: 48.8706,
      longitude: 2.3322,
      adresse: '15 Rue de la Viande, 75005 Paris, France',
    },
    horaires: [
      { jour: 'Lundi', ouverture: '08:00', fermeture: '19:00' },
      { jour: 'Mardi', ouverture: '08:00', fermeture: '19:00' },
      { jour: 'Mercredi', ouverture: '08:00', fermeture: '19:00' },
      { jour: 'Jeudi', ouverture: '08:00', fermeture: '19:00' },
      { jour: 'Vendredi', ouverture: '08:00', fermeture: '19:00' },
      { jour: 'Samedi', ouverture: '08:00', fermeture: '18:00' },
      { jour: 'Dimanche', ouverture: 'fermé', fermeture: 'fermé' },
    ],
    contact: {
      telephone: '+33 1 45 67 89 01',
      email: 'boucherie@tradition.fr',
    },
    articles: [
      {
        id: 'item12',
        storeId: 'store5',
        nom: 'Boeuf Haché',
        categorie: 'viande',
        prixUnitaire: 10.0,
        unite: 'kg',
        stockDisponible: 40,
        imageUrl: 'assets/images/boeuf.jpg',
        description: 'Boeuf haché frais, 5% de matière grasse.',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item13',
        storeId: 'store5',
        nom: 'Saucisses de Porc',
        categorie: 'viande',
        prixUnitaire: 7.0,
        unite: 'kg',
        stockDisponible: 35,
        imageUrl: 'assets/images/saucisses.jpg',
        description: 'Saucisses de porc artisanales.',
        dateMiseAJour: '2025-06-01',
      },
    ],
    promotions: [
      {
        articleId: 'item12',
        reduction: 5, // 5%
        dateDebut: '2025-06-01',
        dateFin: '2025-06-07',
      },
    ],
    // Added dateCreation and dateMiseAJour
    dateCreation: '2025-06-01',
    dateMiseAJour: '2025-06-05',
  },
  {
    id: 'store6',
    nom: 'ShopOnline',
    categorie: 'en ligne',
    localisation: {
      latitude: 0,
      longitude: 0,
      adresse: 'Plateforme en ligne',
    },
    contact: {
      telephone: '+33 1 11 22 33 44',
      email: 'support@shoponline.fr',
      siteWeb: 'https://shoponline.fr',
    },
    articles: [
      {
        id: 'item14',
        storeId: 'store6',
        nom: 'Farine de Blé',
        categorie: 'céréale',
        prixUnitaire: 1.0,
        unite: 'kg',
        stockDisponible: 500,
        imageUrl: 'assets/images/farine.jpg',
        description: 'Farine de blé T55 pour pâtisserie.',
        marque: 'MoulinsDeFrance',
        dateMiseAJour: '2025-06-01',
      },
      {
        id: 'item15',
        storeId: 'store6',
        nom: 'Huile d’Olive',
        categorie: 'autre',
        prixUnitaire: 8.0,
        unite: 'l',
        stockDisponible: 300,
        imageUrl: 'assets/images/huile.jpg',
        description: 'Huile d’olive extra vierge.',
        marque: 'OlivaPure',
        dateMiseAJour: '2025-06-01',
      },
    ],
    promotions: [],
    // Added dateCreation and dateMiseAJour
    dateCreation: '2025-06-01',
    dateMiseAJour: '2025-06-05',
  },
];
